- .github/CODEOWNERS
- .github/PULL_REQUEST_TEMPLATE.md
Fixes [LENS-9](https://consensyssoftware.atlassian.net/browse/LENS-9)
[LENS-9]: https://consensyssoftware.atlassian.net/browse/LENS-9?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LENS-9 - Discovery - Modify PR template on Github

- apps/web/src/components/Shared/Login/New/index.tsx
- apps/web/src/components/utils/hooks/useSimpleDebounce.tsx
- packages/data/constants.ts
- packages/data/contracts.ts
Fixes [LENS-4](https://consensyssoftware.atlassian.net/browse/LENS-4)
[LENS-4]: https://consensyssoftware.atlassian.net/browse/LENS-4?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LENS-4 - Discovery - Create an account

- apps/web/src/components/Shared/Follow.tsx
- packages/data/constants.ts
- packages/data/utils/getEnvConfig.ts
Fixes [LENS-29](https://consensyssoftware.atlassian.net/browse/LENS-29)
[LENS-29]: https://consensyssoftware.atlassian.net/browse/LENS-29?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LENS-29 - Follow feature - Bypass the relayer

- apps/web/src/components/Publication/Actions/Collect/CollectModule.tsx
Fixes [LENS-31](https://consensyssoftware.atlassian.net/browse/LENS-31)
[LENS-31]: https://consensyssoftware.atlassian.net/browse/LENS-31?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LENS-31 - Collect feature - Bypass the relayer

- apps/web/src/components/Shared/Login/New/index.tsx
https://user-images.githubusercontent.com/5815882/234014891-d715950e-0d53-4106-a3ee-06e892da3e44.mov
Fixes [LENS-41](https://consensyssoftware.atlassian.net/browse/LENS-41)
[LENS-41]: https://consensyssoftware.atlassian.net/browse/LENS-41?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LENS-41 - Toggle dispatcher mode on account creation

- apps/web/src/components/Shared/Login/New/index.tsx
- apps/web/src/components/Shared/Navbar/MobileDrawerMenu.tsx
- apps/web/src/components/Shared/Navbar/NavItems/Contact.tsx
- apps/web/src/components/Shared/Navbar/index.tsx
- packages/data/constants.ts
- tests/scripts/apps/web/layout.spec.ts
Fixes [LENS-42](https://consensyssoftware.atlassian.net/browse/LENS-42)
[LENS-42]: https://consensyssoftware.atlassian.net/browse/LENS-42?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(LENS-42): remove 'more nav items' and replace with direct contact link to discord

- apps/prerender/.env.example
- apps/web/.env.example
- pnpm-lock.yaml
- script/bootstrap
- tests/package.json
- tests/scripts/apps/prerender/profile.spec.ts
- tests/scripts/apps/prerender/publication.spec.ts
- tests/scripts/apps/web/explore.spec.ts
- tests/scripts/apps/web/home.spec.ts
- tests/scripts/apps/web/layout.spec.ts
- tests/scripts/apps/web/profile.spec.ts
- tests/scripts/apps/web/publication.spec.ts
Fixes [LENS-66](https://consensyssoftware.atlassian.net/browse/LENS-66)
[LENS-66]: https://consensyssoftware.atlassian.net/browse/LENS-66?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LENS-66 - Make the E2E tests pass on a Linea environment

- apps/web/src/components/Settings/Sidebar.tsx
- packages/data/contracts.ts
Activates "Allowance" in account settings and sets default token + `FeeCollectModule`
Fixes [LENS-62](https://consensyssoftware.atlassian.net/browse/LENS-62)
[LENS-62]: https://consensyssoftware.atlassian.net/browse/LENS-62?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LENS-62 - Collect feature - User can make a post/comment collectable with different rules

- tests/scripts/apps/web/explore.spec.ts
Fixes [LENS-72](https://consensyssoftware.atlassian.net/browse/LENS-72)
[LENS-72]: https://consensyssoftware.atlassian.net/browse/LENS-72?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(LENS-72): update explore test

- tests/scripts/apps/prerender/publication.spec.ts
- tests/scripts/apps/web/publication.spec.ts
Reactivates e2e tests for the "publication" module
Fixes [LENS-71](https://consensyssoftware.atlassian.net/browse/LENS-71)
[LENS-71]: https://consensyssoftware.atlassian.net/browse/LENS-71?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LENS-71 - Update publication tests

- apps/prerender/src/components/Profile.tsx
- apps/web/src/components/Nft/NftFeed.tsx
- apps/web/src/components/Nft/SingleNft.tsx
- apps/web/src/components/Profile/FeedType.tsx
- apps/web/src/components/Profile/index.tsx
- apps/web/src/types/index.d.ts
- packages/data/constants.ts
- packages/data/utils/getEnvConfig.ts
Displays NFTs owned by a profile, on Linea testnet.
Fixes [LENS-73](https://consensyssoftware.atlassian.net/browse/LENS-73)
[LENS-73]: https://consensyssoftware.atlassian.net/browse/LENS-73?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LENS-73 - Use "Zonic" API to gather NFTs on the Profile page

- apps/web/packages/data/constants.ts
Fixes an issue with the `constants` file for the Docker image build
> Fix - Constants used to build the Docker image

- apps/web/src/locales/en/messages.po
- apps/web/src/locales/es/messages.po
- apps/web/src/locales/kn/messages.po
- apps/web/src/locales/ta/messages.po
- apps/web/src/locales/zh/messages.po
Fixes [LENS-XXX](https://consensyssoftware.atlassian.net/browse/LENS-XXX)
> fix APP_NAME issue on Hero component

- apps/web/src/components/Comment/Feed.tsx
- apps/web/src/components/Comment/NoneRelevantFeed.tsx
- apps/web/src/components/Explore/Feed.tsx
- apps/web/src/components/Home/Highlights.tsx
- apps/web/src/components/Home/Timeline/index.tsx
- apps/web/src/components/Mod/Feed.tsx
- apps/web/src/components/Notification/List.tsx
- apps/web/src/components/Profile/Feed.tsx
- apps/web/src/components/Profile/Followers.tsx
- apps/web/src/components/Profile/Following.tsx
- apps/web/src/components/Profile/MutualFollowers/List.tsx
- apps/web/src/components/Profile/NftGallery/Picker.tsx
- apps/web/src/components/Search/Profiles.tsx
- apps/web/src/components/Search/Publications.tsx
- apps/web/src/components/Shared/Modal/Collectors.tsx
- apps/web/src/components/Shared/Modal/Likes.tsx
- apps/web/src/components/Shared/Modal/Mirrors.tsx
Fixes duplication issues on my pages.
Fixes [LENS-XXX](https://consensyssoftware.atlassian.net/browse/LENS-XXX)
> LENS-86 - Content is duplicated when changing/reloading page => fix duplications after fetchMore

- .github/workflows/docker-dev.yml
- apps/web/Dockerfile
Fixes [LENS-XXX](https://consensyssoftware.atlassian.net/browse/LENS-XXX)
> fix: force pnpm version for docker build

- apps/web/packages/data/constants.ts
- blockchain/tasks/MockProfileCreationProxy.ts
- packages/data/constants.ts
Releases a new version of Lineaster
> Release v0.4

- blockchain/hardhat.config.ts
- blockchain/package-lock.json
- blockchain/package.json
Updates dependencies for the 'blockchain' folder, removes vulnerabilities.
Fixes [LENS-103](https://consensyssoftware.atlassian.net/browse/LENS-103)
[LENS-103]: https://consensyssoftware.atlassian.net/browse/LENS-103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LENS-103 - Update 'blockchain' dependencies

- apps/web/packages/data/gardeners.ts
- apps/web/packages/data/lineaster-members.ts
- apps/web/packages/data/verified.ts
- packages/data/gardeners.ts
- packages/data/lineaster-members.ts
- packages/data/verified.ts
Adds some special rights to some profiles
Fixes [LENS-102](https://consensyssoftware.atlassian.net/browse/LENS-102)
[LENS-102]: https://consensyssoftware.atlassian.net/browse/LENS-102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LENS-102 - Whitelist gardeners/staff/verified accounts

- apps/web/src/components/Profile/Details.tsx
Fixes [LENS-87](https://consensyssoftware.atlassian.net/browse/LENS-87)
[LENS-87]: https://consensyssoftware.atlassian.net/browse/LENS-87?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LENS-87 - Change 'Rarible' links to 'Zonic' link on Profile

- .github/workflows/docker-dev-sts.yml
Tries to build the STS image correctly
Fixes [LENS-105](https://consensyssoftware.atlassian.net/browse/LENS-105)
[LENS-105]: https://consensyssoftware.atlassian.net/browse/LENS-105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LENS-105 - Deploy STS instance

- apps/web/src/components/Shared/Login/New/index.tsx
1. Hides the avatar upload feature when creating a handle
2. Adds better error messages on handle creation errors
Fixes [LENS-100](https://consensyssoftware.atlassian.net/browse/LENS-100)
[LENS-100]: https://consensyssoftware.atlassian.net/browse/LENS-100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LENS-100 - Remove avatar upload on handle creation

- apps/web/packages/data/constants.ts
- apps/web/packages/lib/getWalletDetails.ts
- apps/web/src/components/Common/Providers.tsx
- packages/data/constants.ts
- packages/lib/getWalletDetails.ts
Fixes [LENS-101](https://consensyssoftware.atlassian.net/browse/LENS-101)
[LENS-101]: https://consensyssoftware.atlassian.net/browse/LENS-101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(LENS-101): switch to WalletConnect v1 until MM is compatible

- .github/workflows/docker-uat-webapp.yml
- .github/workflows/releaser-uat.yaml
- apps/web/.env.uat
- release-uat.sh
Adds the tooling to deploy the webapp on the UAT environment
Fixes [LENS-93](https://consensyssoftware.atlassian.net/browse/LENS-93)
[LENS-93]: https://consensyssoftware.atlassian.net/browse/LENS-93?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LENS-93 - Deploy Lineaster on the UAT environment

- apps/web/src/components/Shared/Footer/index.tsx
Remove the link to Lenster's Discord
Fixes [LENS-110](https://consensyssoftware.atlassian.net/browse/LENS-100)
[LENS-110]: https://consensyssoftware.atlassian.net/browse/LENS-110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LENS-110 - Remove the link to Lenster Discord

- apps/web/src/components/Shared/Login/New/index.tsx
- blockchain/contracts/mocks/MockProfileCreationProxy.sol
Fixes [LENS-111](https://consensyssoftware.atlassian.net/browse/LENS-111)
[LENS-111]: https://consensyssoftware.atlassian.net/browse/LENS-111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Lens-111: update profile creation smart contract

- blockchain/README.md
- blockchain/hardhat.config.ts
- blockchain/package-lock.json
- blockchain/package.json
- blockchain/tasks/MockProfileCreationProxy.ts
- blockchain/tsconfig.json
- packages/data/index.ts
- pnpm-lock.yaml
Fixes the tooling to deploy our handle creator contract
Fixes [LENS-112](https://consensyssoftware.atlassian.net/browse/LENS-112)
[LENS-112]: https://consensyssoftware.atlassian.net/browse/LENS-112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LENS-112 - Fix the contract deployment tooling

- README-lenster.md
- README.md
Creates a README dedicated to Lineaster
Fixes [LENS-113](https://consensyssoftware.atlassian.net/browse/LENS-113)
[LENS-113]: https://consensyssoftware.atlassian.net/browse/LENS-113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LENS-113 - Update the readme file

- apps/web/src/components/Shared/Footer/index.tsx
- apps/web/src/locales/en/messages.po
- apps/web/src/locales/es/messages.po
- apps/web/src/locales/kn/messages.po
- apps/web/src/locales/ta/messages.po
- apps/web/src/locales/zh/messages.po
1. Adds a link to Lineaster's Twitter account
2. 2. Updates the translations catalog
Fixes [LENS-114](https://consensyssoftware.atlassian.net/browse/LENS-114)
[LENS-114]: https://consensyssoftware.atlassian.net/browse/LENS-114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LENS-114 - Add Twitter link in footer

- tests/scripts/apps/prerender/profile.spec.ts
Fixes the tests that are launched once a day against the DEV environment
> Fix nightly tests (ignore prerender tests)

- apps/web/packages/data/gardeners.ts
- apps/web/packages/data/lineaster-members.ts
- apps/web/packages/data/verified.ts
- packages/data/gardeners.ts
- packages/data/lineaster-members.ts
- packages/data/verified.ts
Adds support team as staff, verified and members lists
> Verify profiles

- .github/workflows/docker-dev-webapp.yml
- .github/workflows/docker-uat-webapp.yml
- apps/web/.env.development
- apps/web/.env.example
- apps/web/.env.uat
- apps/web/Dockerfile
- apps/web/packages/data/constants.ts
- packages/data/constants.ts
Simplifies the split between DEV and UAT image build
> Better split between DEV and UAT environments on build

- apps/web/src/components/Shared/Login/New/index.tsx
Displays clearer error messages on handle creation
> Better handle creation error messages

- apps/web/packages/data/gardeners.ts
- apps/web/packages/data/lineaster-members.ts
- apps/web/packages/data/verified.ts
- packages/data/gardeners.ts
- packages/data/lineaster-members.ts
- packages/data/verified.ts
Verifies `hiroprotagonist`'s profile
> Verify hiroprotagonist profile

- apps/web/src/components/Shared/Login/New/index.tsx
> Fix a typo in error messages

- apps/web/src/components/Shared/Login/New/index.tsx
When a user's handle is created on-chain but not indexed by the Lens API, gives the ability to burn the handle to restart the process.
Fixes [LENS-126](https://consensyssoftware.atlassian.net/browse/LENS-126)
[LENS-126]: https://consensyssoftware.atlassian.net/browse/LENS-126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LENS-126 - When a handle was not indexed by the API, give the ability to burn it

- apps/web/packages/ui/src/Checkbox.tsx
- apps/web/src/components/Nft/SingleNft.tsx
- apps/web/src/components/Profile/Details.tsx
- apps/web/src/components/Profile/Feed.tsx
- apps/web/src/components/Profile/FeedType.tsx
- apps/web/src/components/Profile/Filters/MediaFilter.tsx
- apps/web/src/components/Publication/Actions/Menu/Delete.tsx
- apps/web/src/components/Publication/Actions/Menu/Embed.tsx
- apps/web/src/components/Publication/Actions/Menu/Permalink.tsx
- apps/web/src/components/Publication/Actions/Menu/Report.tsx
- apps/web/src/components/Publication/Actions/Menu/index.tsx
- packages/ui/src/Checkbox.tsx
- packages/ui/src/TabButton.tsx
Fixes [LENS-47](https://consensyssoftware.atlassian.net/browse/LENS-47)
[LENS-47]: https://consensyssoftware.atlassian.net/browse/LENS-47?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LENS-47: [UI] Adapt Profile page styles

- apps/web/src/components/Shared/Login/New/index.tsx
Reverts ConsenSys/lineaster#92
> Revert "LENS-126 - When a handle was not indexed by the API, give the ability to burn it"

- apps/web/src/components/Comment/Feed.tsx
- apps/web/src/components/Comment/NoneRelevantFeed.tsx
- apps/web/src/components/Explore/Feed.tsx
- apps/web/src/components/Home/Highlights.tsx
- apps/web/src/components/Home/Timeline/index.tsx
- apps/web/src/components/Mod/Feed.tsx
- apps/web/src/components/Notification/List.tsx
- apps/web/src/components/Profile/Feed.tsx
- apps/web/src/components/Profile/Followers.tsx
- apps/web/src/components/Profile/Following.tsx
- apps/web/src/components/Profile/MutualFollowers/List.tsx
- apps/web/src/components/Search/Profiles.tsx
- apps/web/src/components/Search/Publications.tsx
- apps/web/src/components/Shared/Login/New/Pending.tsx
- apps/web/src/components/Shared/Modal/Collectors.tsx
- apps/web/src/components/Shared/Modal/Likes.tsx
- apps/web/src/components/Shared/Modal/Mirrors.tsx
- apps/web/src/components/Shared/Unfollow.tsx
- apps/web/src/components/utils/uniqBy.ts
Fixes [LENS-121](https://consensyssoftware.atlassian.net/browse/LENS-121)
[LENS-121]: https://consensyssoftware.atlassian.net/browse/LENS-121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(LENS-121): Multiple lists items are duplicated

- apps/web/src/components/Messages/Composer.tsx
- apps/web/src/components/Messages/MessageHeader.tsx
- apps/web/src/components/Messages/PreviewList.tsx
- apps/web/src/components/Messages/index.tsx
- apps/web/src/components/Profile/Following.tsx
- apps/web/src/components/Shared/Follow.tsx
- apps/web/src/components/Shared/Unfollow.tsx
- apps/web/src/components/Shared/UserProfile.tsx
- apps/web/src/tracking.ts
Fixes [LENS-46](https://consensyssoftware.atlassian.net/browse/LENS-46)
[LENS-46]: https://consensyssoftware.atlassian.net/browse/LENS-46?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LENS-46: [UI] Adapt chat page styles

- apps/prerender/src/components/Profile.tsx
- apps/prerender/src/components/Publication.tsx
- apps/prerender/src/components/Shared/SinglePublication.tsx
- apps/web/packages/lib/imageProxy.ts
- packages/lib/imageProxy.ts
- tests/scripts/apps/web/publication.spec.ts
- tests/scripts/packages/lib/getAvatar.spec.ts
- tests/scripts/packages/lib/imageProxy.spec.ts
> fix: No CDN for user content
